# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://chautunglam.me/property-site/"

# This will help you track who's visiting your website.
# tracking:
#   google_analytics: "UA-43729070-14"

banner:
    name: "Ocean front land"
    button: "Learn More"

one:
    header: "A good location"
    content: "Imagine the possibility of a Satellite golf club property on the west coast of Cape Breton, Nova Scotia, with easy access to the world class Cabot Links and Cabot Cliffs golf courses, or a day trip to arrive at any golf course on Cape Breton. Members of your club could rotate to visit and golf in Cape Breton while staying at a club owned property that will appreciated in value as time passes. This ocean front parcel offers approximately 68 acres, with ample room for a seaside clubhouse, individual residences or condos, putting green, driving range, and even the possibility of a private airstrip. This triangular shaped peninsula offers a long sandy beach on the ocean, warm water temperatures, beautiful westward views of sunsets on the private beach over the sea, and southward views over the adjacent salt water inlet and pond where nature abounds. Have verification letter from local municipality that they place no restrictions on developement of property i.e. Comercial , or residential. Market search failed to reveal any comparable nearby properties at any price. Asking 3.2 million USD"
