# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://chautunglam.me/property-site/"

# This will help you track who's visiting your website.
# tracking:
#   google_analytics: "UA-43729070-14"

banner:
    name: "Ocean front land"
    button: "Learn More"

one:
    header: "A good location"
    content: "Imagine the possibility of a Satellite golf club property on the west coast of Cape Breton, Nova Scotia, with easy access to the world class Cabot Links and Cabot Cliffs golf courses, or a day trip to arrive at any golf course on Cape Breton. Members of your club could rotate to visit and golf in Cape Breton while staying at a club owned property that will appreciated in value as time passes."

two:
    first_section:
        image:
            path: "images/ocean-land.jpg"
            alt: ""
        header: "Land by the ocean"
        content: "This ocean front parcel offers approximately 68 acres, with ample room for a seaside clubhouse, individual residences or condos, putting green, driving range, and even the possibility of a private airstrip."

    second_section:
        image:
            path: "images/beach.png"
            alt: ""
        header: "Warm beach, beautiful sunsets"
        content: "This triangular shaped peninsula offers a long sandy beach on the ocean, warm water temperatures, beautiful westward views of sunsets on the private beach over the sea, and southward views over the adjacent salt water inlet and pond where nature abounds"

    third_section:
        image:
            path: "images/development.png"
            alt: ""
        header: "No restrictions on property development"
        content: "Have verification letter from local municipality that they place no restrictions on developement of property i.e. Comercial , or residential."

    fourth_section:
        header: "A lot of places for entertainment"
        content: "There are a lot of golf courses to be found around the area. Take a look at [this](http://scoregolf.com/golf-course-guide/cape-breton-island-golf-courses) for more information about the golf courses in Cape Breton"

three:
    title: "More information on nearby golf courses"
    content:
        - header: "Cabot Cliffs"
          content: "Exquisitely carved out of the breathtaking Cape Breton landscape, with postcard worthy panoramas vying for your attention and rich, rolling fairways waiting to reward your creativity, this is linksland golf at its best.  Built by dreamers, for dreamers.

          [Read more](https://www.cabotlinks.com/golf/cabot-cliffs/)"
          icon: "fa-paper-plane-o"

        - header: "Cabot Links"
          content: "Nestled along the breathtaking shores of Cape Breton, Cabot Links is your invitation to a destination, a land, and a journey like no other. To a spellbinding time and place reminiscent of golf’s beginnings, born out of our passion for authentic linksland golf. And where unbelievable shots, extraordinary experiences, and unforgettable memories await you each and every day.

          [Read more](https://www.cabotlinks.com/golf/cabot-links/)"
          icon: "fa-paper-plane-o"

        - header: "The Cape Breton Highlands"
          content: "The Cape Breton Highlands Golf Course is one of a kind. Conceived and constructed under the watchful eye of world-renowned designer Stanley Thompson, it is a classic 18-hole, par 72 course carved out of one of Canada’s most pristine wildernesses. Come experience golfing in a way you never have before! Our course has beautiful views around every corner, as well as nature being all around you while playing through the Cape Breton National Park.

          [Read more](http://kelticlodge.ca/golf/)"
          icon: "fa-paper-plane-o"

        - header: "Baddeck Forks 9-hole Golf Course"
          content: "Baddeck Forks Golf Club is located along the beautiful Baddeck River which empties into the Bras d'Or lakes - an inland sea in the heart of Cape Breton Island.

          [Read more](http://www.baddeckforksgolf.com/)"
          icon: "fa-paper-plane-o"

        - header: "Seaview Golf & Country Club"
          content: "SEAVIEW GOLF AND COUNTRY CLUB IS RANKED AS ONE OF THE TOP 10 COURSES IN NOVA SCOTIA BY WESTJET MAGAZINE

          [Read more](http://seaviewgcc.com/)"
          icon: "fa-paper-plane-o"

        - header: "Bell Bay Golf Club"
          content: "One of Cape Breton Island’s premier golf courses, Bell Bay overlooks the Bras d’Or Lakes in beautiful Baddeck. This Thomas McBroom masterpiece has incredible views from virtually every hole. The course was sculpted into the natural features of the land to make each hole very distinctive.

          [Read more](http://www.bellbaygolfclub.com/)"
          icon: "fa-paper-plane-o"


four:
    header: "Current price"
    content: "Market search failed to reveal any comparable nearby properties at any price. Asking 2.9 million USD"
